on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

name: Build

jobs:
  create-boot-image:
    name: Create boot image for EDK2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt install git make gcc g++ device-tree-compiler bc bison flex libssl-dev libncurses-dev python3-ply python3-git libgmp3-dev libmpc-dev gcc-aarch64-linux-gnu
      - name: Run build script
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make ginkgo_defconfig
          make -j$(nproc --all)
      - uses: actions/upload-artifact@v3
        with:
          name: Redmi Note 8
          path: ./arch/arm64/boot/Image
      - uses: actions/upload-artifact@v3
        with:
          name: Redmi Note 8
          path: ./arch/arm64/boot/dts/qcom/sm6125-xiaomi-ginkgo.dtb
